### ISSUE TITLE
Error caused by NCC dependancy?

### ISSUE THREAD

**Issue by morlando016** [Checkmarx/kics-github-action#81]
We are on KICS action version 1.6. It seems like an underlying dependancy of KICS has been updated and broken the KICS action. I believe this dependancy is NCC and the related issue from their repo is here https://github.com/vercel/ncc/issues/805

```
> kics-github-action@1.0.0 build
> ncc build src/main.js

ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1855992)
    at ncc (/app/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1860457)
    at runCmd (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55128)
    at 819 (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51698)
    at __webpack_require__ (/app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:5[904](https://github.com/HylandSoftware/Hyland.Experience.Iam.Api/actions/runs/4419152099/jobs/7747213148#step:6:905)8)
    at /app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59260
    at /app/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:59321
    at Object.<anonymous> (/app/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/app/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:[920](https://github.com/HylandSoftware/Hyland.Experience.Iam.Api/actions/runs/4419152099/jobs/7747213148#step:6:921):27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by zach-vega** [comment]
I get the same when pinning v1.6.2 of the kics-github-action. This occurs after the kics scan has completed. Additional (possibly) relevant detail: 

`(1/7) Installing c-ares (1.18.1-r1)
(2/7) Installing libgcc (12.2.1_git20220924-r4)
(3/7) Installing icu-data-en ([72](https://github.com/liberty-lake-cloud/Vega.CloudInquisitor/actions/runs/4419191988/jobs/7747304274#step:7:73).1-r1)
Executing icu-data-en-72.1-r1.post-install
*
(4/7) Installing libstdc++ (12.2.1_git20220924-r4)
* If you need ICU with non-English locales and legacy charset support, install
* package icu-data-full.
*
(5/7) Installing icu-libs (72.1-r1)
(6/7) Installing nodejs (18.14.2-r0)
(7/7) Installing npm (9.1.2-r0)
Executing busybox-1.35.0-r29.trigger`

**Comment by AlilNinja** [comment]
just to add on, our workaround for now has been to downgrade the `Checkmarx/kics-github-action` to `v1.5`. That version still seems to work

**Comment by brucetieu** [comment]
@morlando016 @zach-vega We believe this is caused by version 1.6.12 of [kics](https://github.com/Checkmarx/kics) being released. Therefore, we rolled back the version of the kics-github-action to use v1.5 (uses: checkmarx/kics-github-action@v1.5), and the error went away.

**Comment by gabriel-cx** [comment]
Hi,

Kindly use the latest version of this KICS github action (v1.6.3).
A fix was merged. The action should now work without a problem.

Please close this issue if the problem is no longer present.

**Comment by gabriel-cx** [comment]
Looks like [KICS github action v1.6.3 ](https://github.com/Checkmarx/kics-github-action/releases/tag/v1.6.3) is working fine: this issue is no longer present.
Kindly use that version.
